os: bionic
language: node_js
node_js:
  - lts/*
  - node
before_install:
  - |-
    if [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_BRANCH == "master" ];
     then
        echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc;
      else
        echo "//registry.npmjs.org/:_authToken=\${NPM_INSTALL_TOKEN}" > ~/.npmrc;
    fi
  - 'git config --global url."git@github.com:".insteadOf "https://github.com/"'
  - npm i -g @labshare/lsc codecov
install:
  - npm install
  - npm run build
script:
  - npm run coverage
  - codecov
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  allow_failures:
    - node_js: node
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run semantic-release
